# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CUIucs45_MhLLKGWt7Pz1vd-xxLzOun5
"""

pwd

from google.colab import drive
drive.mount("/content/drive/")

pwd

cd drive/My\ Drive/customer analytics/

!ls

import os
os.chdir('/content/drive/My Drive/customer analytics')
!mkdir analytic
!unzip -q ibm-watson-marketing-customer-value-data (2).zip   -d analytic/

cd analytic/

!ls

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

#reading the customer_value_analysis data
df = pd.read_csv("WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv")
df.head(4)

#columns in dataset
df.columns

df.info()

df.isnull().count

df.isnull().sum()

#Full description of the dataset
df.describe()

df.groupby("Response").count()["Customer"]

ax = df.groupby("Response").count()["Customer"]

import seaborn as sns
x = sns.countplot('Response',data = df)
plt.ylabel('Total number of Response')
plt.show()

df.groupby("Renew Offer Type").count()["Customer"]

#Response rate by offer type
plt.figure(figsize=(8,4))
ax = sns.countplot('Response',hue = 'Renew Offer Type' ,data = df)
plt.ylabel('Total number of Response')
plt.show()

#customer response rate by Education
plt.figure(figsize=(8,4))
ax = sns.countplot('Response',hue = 'Education' ,data = df)
plt.ylabel('Total number of Response')
plt.show()

#Response rate by sales channel
plt.figure(figsize=(8,4))
ax = sns.countplot('Response',hue = 'Sales Channel' ,data = df)
plt.ylabel('Total number of Response')
plt.show()

#Response rate by number of policy taken
plt.figure(figsize=(10,7))
ax = sns.countplot('Response',hue = 'Policy' ,data = df)
plt.ylabel('Total number of Response')
plt.show()

plt.figure(figsize=(10,7))
ax = sns.countplot('Response',hue = 'Vehicle Class' ,data = df)
plt.ylabel('Total number of Response')
plt.show()

plt.figure(figsize=(10,7))
ax = sns.countplot('Response',hue = 'Vehicle Size' ,data = df)
plt.ylabel('Total number of Response')
plt.show()

df1 = df["Response"]

df = df.drop("Response",axis = 1).copy()

df.columns

for i in df.columns:
  print(type(i))

corr = df.corr(method = "pearson" )

sns.heatmap(corr)

